apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: wi-test
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: simple-wi-ksa
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
