---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gxlb-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
#    cloud.google.com/backend-config: '{"default": "mybackendconfig"}'
#    networking.gke.io/managed-certificates: my-managed-cert
spec:
  defaultBackend:
    service:
      name: web
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /api
        pathType: ImplementationSpecific
        backend:
          service:
            name: api
            port:
              number: 80
      - path: /payments
        pathType: ImplementationSpecific
        backend:
          service:
            name: payments
            port:
              number: 80
      - path: /currency
        pathType: ImplementationSpecific
        backend:
          service:
            name: currency
            port:
              number: 80
