---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "log-tcp-connection"
  annotations:
    description: "Log TCP connections"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
  - call: "tcp_sendmsg"
    syscall: false
    args:
    - index: 0
      type: "sock"
    - index: 2
      type: int
    selectors:
    - matchPIDs:	# match all PIDs
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: "tcp_close"
    syscall: false
    args:
    - index: 0
      type: "sock"
