apiVersion: v1
kind: Service
metadata:
  name: productpage-external
  namespace: bookinfo
spec:
  type: LoadBalancer
  selector:
    app: productpage
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9080
