---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: store
spec:
 # route binding (https://gateway-api.sigs.k8s.io/concepts/api-overview/#route-binding)
 parentRefs:
 - kind: Gateway
   name: internal-http
 hostnames:
 - "store.example.com"
 rules:
 - backendRefs:
   - name: store-v1
     port: 8080
 - matches:
   - headers:
     - name: env
       value: canary
   backendRefs:
   - name: store-v2
     port: 8080
 - matches:
   - path:
       value: /de
   backendRefs:
   - name: store-german
     port: 8080
